-- =====================================================================
-- SISTEMA_VENDAS_DDL_V1.0
-- SCRIPT DE IMPLANTACAO DO BANCO DE DADOS (DDL)
-- SISTEMA DE VENDAS E ANALISE COMERCIAL
-- Compativel com Oracle Database 23ai / Oracle APEX
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. LIMPEZA DO AMBIENTE (OPCIONAL - EXECUTE SE QUISER RESETAR O SCHEMA)
-- ---------------------------------------------------------------------
DROP TABLE tb_auditoria_venda CASCADE CONSTRAINTS;
DROP TABLE tb_venda_item      CASCADE CONSTRAINTS;
DROP TABLE tb_venda           CASCADE CONSTRAINTS;
DROP TABLE tb_produto         CASCADE CONSTRAINTS;
DROP TABLE tb_vendedor        CASCADE CONSTRAINTS;
DROP TABLE tb_cliente         CASCADE CONSTRAINTS;
DROP TABLE tb_categoria       CASCADE CONSTRAINTS;
DROP TABLE tb_calendario      CASCADE CONSTRAINTS;

-- ---------------------------------------------------------------------
-- 1. TABELA: TB_CLIENTE  (sem dependencias)
-- ---------------------------------------------------------------------
CREATE TABLE tb_cliente (
    id_cliente   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(150) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    cpf          VARCHAR2(11),
    dt_cadastro  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_tb_cliente     PRIMARY KEY (id_cliente),
    CONSTRAINT uq_tb_cliente_email UNIQUE (email),
    CONSTRAINT uq_tb_cliente_cpf   UNIQUE (cpf),
    CONSTRAINT ck_tb_cliente_ativo CHECK (ativo IN ('S', 'N'))
);

-- ---------------------------------------------------------------------
-- 2. TABELA: TB_VENDEDOR  (sem dependencias)
-- ---------------------------------------------------------------------
CREATE TABLE tb_vendedor (
    id_vendedor  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(150) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    dt_admissao  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_tb_vendedor      PRIMARY KEY (id_vendedor),
    CONSTRAINT uq_tb_vendedor_email UNIQUE (email),
    CONSTRAINT ck_tb_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);

-- ---------------------------------------------------------------------
-- 3. TABELA: TB_CATEGORIA  (sem dependencias)
-- ---------------------------------------------------------------------
CREATE TABLE tb_categoria (
    id_categoria  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_tb_categoria     PRIMARY KEY (id_categoria),
    CONSTRAINT uq_tb_categoria_nome UNIQUE (nome)
);

-- ---------------------------------------------------------------------
-- 4. TABELA: TB_PRODUTO  (depende de TB_CATEGORIA)
-- ---------------------------------------------------------------------
CREATE TABLE tb_produto (
    id_produto    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria  NUMBER NOT NULL,
    sku           VARCHAR2(30) NOT NULL,
    nome          VARCHAR2(150) NOT NULL,
    preco_unit    NUMBER(12,2) NOT NULL,
    ativo         CHAR(1) DEFAULT 'S' NOT NULL,
    dt_cadastro   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_tb_produto   PRIMARY KEY (id_produto),
    CONSTRAINT uq_tb_produto_sku UNIQUE (sku),
    CONSTRAINT fk_tb_produto_categoria FOREIGN KEY (id_categoria)
        REFERENCES tb_categoria (id_categoria),
    CONSTRAINT ck_tb_produto_preco CHECK (preco_unit > 0),
    CONSTRAINT ck_tb_produto_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE INDEX ix_prod_categoria ON tb_produto (id_categoria);

-- ---------------------------------------------------------------------
-- 5. TABELA: TB_VENDA  (depende de TB_CLIENTE e TB_VENDEDOR)
-- ---------------------------------------------------------------------
CREATE TABLE tb_venda (
    id_venda        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      NUMBER NOT NULL,
    id_vendedor     NUMBER NOT NULL,
    dt_venda        DATE DEFAULT SYSDATE NOT NULL,
    valor_liquido   NUMBER(14,2) DEFAULT 0 NOT NULL,
    canal           VARCHAR2(20) NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_tb_venda PRIMARY KEY (id_venda),
    CONSTRAINT fk_tb_venda_cliente FOREIGN KEY (id_cliente)
        REFERENCES tb_cliente (id_cliente),
    CONSTRAINT fk_tb_venda_vendedor FOREIGN KEY (id_vendedor)
        REFERENCES tb_vendedor (id_vendedor),
    CONSTRAINT ck_tb_venda_canal  CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    CONSTRAINT ck_tb_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    CONSTRAINT ck_tb_venda_valor  CHECK (valor_liquido >= 0)
);

CREATE INDEX ix_venda_dt        ON tb_venda (dt_venda);
CREATE INDEX ix_venda_cliente   ON tb_venda (id_cliente);
CREATE INDEX ix_venda_vendedor  ON tb_venda (id_vendedor);

-- ---------------------------------------------------------------------
-- 6. TABELA: TB_VENDA_ITEM  (depende de TB_VENDA e TB_PRODUTO)
-- ---------------------------------------------------------------------
CREATE TABLE tb_venda_item (
    id_venda_item       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda            NUMBER NOT NULL,
    id_produto          NUMBER NOT NULL,
    quantidade          NUMBER(10) NOT NULL,
    valor_unit          NUMBER(12,2) NOT NULL,
    percentual_desconto NUMBER(5,2) DEFAULT 0 NOT NULL,
    valor_total         NUMBER(14,2)
        GENERATED ALWAYS AS (
            ROUND(quantidade * valor_unit * (1 - percentual_desconto / 100), 2)
        ) VIRTUAL,
    CONSTRAINT pk_tb_venda_item PRIMARY KEY (id_venda_item),
    CONSTRAINT fk_tb_item_venda FOREIGN KEY (id_venda)
        REFERENCES tb_venda (id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_tb_item_produto FOREIGN KEY (id_produto)
        REFERENCES tb_produto (id_produto),
    CONSTRAINT ck_tb_item_qtd       CHECK (quantidade > 0),
    CONSTRAINT ck_tb_item_valor     CHECK (valor_unit >= 0),
    CONSTRAINT ck_tb_item_desconto  CHECK (percentual_desconto BETWEEN 0 AND 50)
);

CREATE INDEX ix_item_venda   ON tb_venda_item (id_venda);
CREATE INDEX ix_item_produto ON tb_venda_item (id_produto);

-- ---------------------------------------------------------------------
-- 7. TABELA EXTRA/BONUS: TB_AUDITORIA_VENDA (nao exigida pelo enunciado)
-- ---------------------------------------------------------------------
CREATE TABLE tb_auditoria_venda (
    id_auditoria  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda      NUMBER NOT NULL,
    operacao      VARCHAR2(10) NOT NULL,
    usuario_bd    VARCHAR2(128) NOT NULL,
    dt_evento     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detalhes      VARCHAR2(4000),
    CONSTRAINT pk_tb_auditoria_venda PRIMARY KEY (id_auditoria)
);

-- ---------------------------------------------------------------------
-- 8. TABELA EXTRA/BONUS: TB_CALENDARIO (nao exigida pelo enunciado)
-- ---------------------------------------------------------------------
CREATE TABLE tb_calendario (
    dt_ref            DATE NOT NULL,
    ano               NUMBER(4) NOT NULL,
    mes               NUMBER(2) NOT NULL,
    dia               NUMBER(2) NOT NULL,
    trimestre         NUMBER(1) NOT NULL,
    nome_mes          VARCHAR2(15) NOT NULL,
    dia_semana        NUMBER(1) NOT NULL,
    nome_dia_semana   VARCHAR2(15) NOT NULL,
    CONSTRAINT pk_tb_calendario PRIMARY KEY (dt_ref)
);
